### ISSUE TITLE
No .egg file to download here.

### ISSUE THREAD

**Issue by Malachiasz** [JohnDoee/deluge-streaming#1]
Here you attach .egg files http://forum.deluge-torrent.org/viewtopic.php?f=9&t=49679
But if somebody stumbles upon your github it's not so obvious where is .egg to download or how to make it yourself. 
Anyway, thx for plugin. Seems working.

**Comment by JohnDoee** [comment]
There we go.

Man, that menu point is not very obvious.

Thanks, always nice to get some feedback :).
