### ISSUE TITLE
open stream with a httpS link

### ISSUE THREAD

**Issue by J2501** [JohnDoee/deluge-streaming#10]
Is it possible to open the stream in a https link ?

This plugin is really usefull, but it is the only "weak" point in my setup.

**Comment by JohnDoee** [comment]
Self-signed or do you want to be able to provide your own ?

Most of the work is really in the dialogs, actual implementation is quite easy.

**Comment by J2501** [comment]
No matter, I use both self-signed and a letsencrypt certificate _(when I got problem to configure my letsencrypt certificate for a specific service I use a self-signed ...)_

Perhaps you can reuse the location for the certificate used by Deluge (if you don't activated HTTPS on Deluge WebUI, you probably don't want HTTPS on your stream URL). 

Thank you for your job

**Comment by JohnDoee** [comment]
Working with the GUI components again brought back repressed memories.

A lot has been changed so I hope it works as expected :smile:

**Comment by JohnDoee** [comment]
The new release can be found here https://github.com/JohnDoee/deluge-streaming/releases/tag/0.7.1 - Please report back if you hit any errors or major problems.

**Comment by J2501** [comment]
I do not use the GUI but the WebUI, I should have said that before ... sorry .

Anyway thank you for your work.

_I'm hosting a seedbox for my friends and I, so your plugin is very useful for us : we don't need to launch an SFTP client and find the file in the good folder, just 2 clic on the webUI and the video is playing.
I use HTTPS for privacy reasons because my packets go through the internet (not only through my LAN)_

**Comment by J2501** [comment]
After a restart it works perfectly !
