### ISSUE TITLE
Not working in WebUI

### ISSUE THREAD

**Issue by zimmertr** [JohnDoee/deluge-streaming#11]
Is the WebUI supported for this plugin? Nothing occurs when I right click on a torrent, or file listed on the "Files" tab, and click Stream.

**Comment by J2501** [comment]
I only use the WebUI and the plugin works perfectly (with deluge 1.3.10).
Did you try to restart Deluge/webUI  ?

**Comment by JohnDoee** [comment]
As @J2501 said, it should work with the Web-UI. I test with both 1.3.6 and 1.3.11 normally. Does it work with GTK-UI ?

I'd be happy if you can check Deluge Daemon output for errors / Python exceptions, you do not need to enable any special logging for this and it should be written to stderr by Deluge Daemon. You can start Deluge Daemon in the foreground simply by running `deluged -d`

Also, please check your Javascript console for errors. This can be opened by pressing ctrl + shift + i in Firefox or ctrl + shift + j in Chrome and select the "console" tab. Errors will be in red and probably say streaming.js somewhere in the line.

If you have any ideas on how I can reproduce the error or pointers what it might be, I'm also very interested in that. The streaming plugin might choke on some configuration you made if it was something the plugin did not expect.
