### ISSUE TITLE
Open directly with vlc

### ISSUE THREAD

**Issue by cirelli94** [JohnDoee/deluge-streaming#12]
Is it possible to add an option to start it directly in VLC?

**Comment by JohnDoee** [comment]
What OS ?

**Comment by cirelli94** [comment]
Ubuntu 16.10
http://i.imgur.com/1jxELhn.png This is wonderful if I run deluge-web, but have an option to run VLC would be great!

**Comment by nwgat** [comment]
implement something like 
Right Click > Play in $player
player="mpv.exe $url"

also auto copy to clipboard? option

**Comment by joaoeudes7** [comment]
please '-'

**Comment by JohnDoee** [comment]
I made a fix for Windows, linux version is still pending. You can see it https://github.com/JohnDoee/deluge-streaming under "Open directly in your video player"

**Comment by sojusnik** [comment]
Can't wait for the linux version!

**Comment by avncharlie** [comment]
Is it possible for this to be implemented on Mac?

**Comment by JohnDoee** [comment]
@avncharlie In theory it is, the problem is that I don't have access to a Mac to develop it on. A quick Google search does not reveal any easy way for me to build and package it without one.

If you have any knowledge regarding OSX development without a Mac, feel free to share it.

The Linux version just needs a bit of UI and packaging, so OSX will be the only one left in the cold :slightly_smiling_face:

**Comment by avncharlie** [comment]
I don't have any experience like that sorry.  But if you wanted me to try or run anything on my Mac, I'd be more than happy too. Thanks for your work on this plugin

**Comment by HaleTom** [comment]
Is there any equivalent of StreamProtocol for Linux?

**Comment by LeoUfimtsev** [comment]
I'd be happy to test things on linux. Would like to have this feature. I can compile stuff.

**Comment by alvitawa** [comment]
I figured out how to directly open the streams on vlc on linux (takes a little bit of work):

Make file `vlc_open_stream.py` and put it in ~/bin/ with the following content:

    #!/usr/bin/env python3

    # Called by ~/.local/share/applications/stream_scheme_handler.desktop
    # which is added to mimeapps.list with `xdg-mime default stream_scheme_handler.desktop x-scheme-handler/stream+http`

    import sys
    import os

    arg = sys.argv[1]

    url = arg.split(':', 1)[1]

    os.system('vlc http:' + url)

Make file `stream_scheme_handler.desktop` and put it in ~/.local/share/applications with content:

    [Desktop Entry]
    Type=Application
    Name=Stream Scheme Handler
    Exec=~/bin/vlc_open_stream.py %u
    StartupNotify=false
    MimeType=x-scheme-handler/stream+http;

Run command:

    xdg-mime default stream_scheme_handler.desktop x-scheme-handler/stream+http

Now it should work. This configures xdg-open to understand stream+http:%url.
You can put the python script somewhere other than ~/bin if you want, just make sure to alter the path in the desktop file as well.
