### ISSUE TITLE
In a fresh docker start, plugin is not properly loaded

### ISSUE THREAD

**Issue by Nottt** [JohnDoee/deluge-streaming#16]
I want to put this in my docker image by default, I make sure the .egg file is in the plugin folder before starting deluge.

This is the only plugin of the many I use, that start like this :

![image](https://user-images.githubusercontent.com/13532436/32357508-97308bca-c024-11e7-9808-d5835234082d.png)

I have to manually install via GTK UI it so that information are properly loaded. I see no errors anywhere.

**Comment by JohnDoee** [comment]
Is it possible you can share your Docker file? Or at least, give me Deluge version, Docker FROM image and one or more other plugins you are testing with.

I've tried to reproduce it but was unable to.

**Comment by Nottt** [comment]
https://hub.docker.com/r/nottt/easy-deluge/

Also, what would be the most sensible defaults ?
