### ISSUE TITLE
Web UI Support

### ISSUE THREAD

**Issue by gustebeast** [JohnDoee/deluge-streaming#2]
Just would like to say I would very much appreciate having web ui support if you have the time to add it. When I try to use this on a remote headless debian server I get 

[ERROR   ] 11:38:50 init:50 Unable to enable plugin!
[ERROR   ] 11:38:50 init:51 'session' object has no attribute 'get_settings'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/plugins/init.py", line 48, in enable
    self.plugin.enable()
  File "/home/gus/.config/deluge/plugins/Streaming-0.3.1-py2.7.egg/streaming/core.py", line 475, in enable
    settings = session.get_settings()
AttributeError: 'session' object has no attribute 'get_settings'

**Comment by JohnDoee** [comment]
There we go, check out v0.4.0

I've only tested with 1.3.6, but it should work for all 1.3.x

**Comment by gustebeast** [comment]
Thank you for coming back to develop this! With your version the "Stream this file" option now appears, but it does not work.

First though a key question: will this plugin allow me to stream a file currently downloading? I know that sequential downloading has become taboo in the torrent world, but I feel this kind of implementation would be nice. Its not a default setting that all torrents use, its just for that rare occurrence when you need to stream a movie file immediately. The pieces plugin used to support it but now that is out of date, and after thorough research I've found that there is pretty much no way to get sequential downloading support on Deluge, so if you could provide it here it would be incredibly valuable.

I ask because I already have a plex server which allows me to stream movie files once they are complete, so if this only worked for completed torrents it wouldnt be of much use. Either way though I will share with you the bugs I encountered.

On server load
http://hastebin.com/udepuwemow.scala

On start stream of .mkv file (completely downloaded):
http://hastebin.com/jiyohulipe.rb

**Comment by JohnDoee** [comment]
It seems like you're hitting a bug I haven't seen, you'll need to share your deluge daemon version, output of `deluged --version` should be fine.

Yes, it can stream while downloading that's what it's designed for. My main hobby project is a semi-alternative to Plex server (has a other goals than Plex server).

First, it is not 100% sequential, and if your internet is fast enough, it'll eventually just download the file normally. You can also seek while downloading, that will make it download the part of the file you want to watch. Something more like smart sequential downloading.

Second, sequential download is only bad in a number of situations, not all. A rule of thumb is, if there is only one (slow) seeder, then sequential is bad. Other situations are between _not-perfect_ and _doesn't matter_.

**Comment by gustebeast** [comment]
Awesome! Glad to hear someone else thinks its a valuable feature. Very excited to use this.

$ deluged --version
deluged: 1.3.3
libtorrent: 0.15.10.0

**Comment by JohnDoee** [comment]
So, you're running Wheezy ? That's what I tested with, at least.

I can recommend upgrading to a newer version of Deluge and/or installing [ltConfig](http://forum.deluge-torrent.org/viewtopic.php?t=42887) - pick the high performance seed profile, it improved performance for me. I tested a lot with the TPB AFK documentary, and click to start time was normally 15-30 seconds.

I just put up a new version https://github.com/JohnDoee/deluge-streaming/releases/tag/0.4.1

**Comment by gustebeast** [comment]
I just installed deluge using apt-get install deluge [...] to get the version I have. How would I go about getting a newer version?

Also I tested 0.4.1 and I got a link successfully without error. My next question is, how would I go about watching the stream? I tried replacing 127.0.0.1 with my domain name and put the link into VLC, but it said the input couldn't be opened. I was doing this with a file that had already completely downloaded if that is the trouble.

Having a link I could put into VLC on my computer would work well, although to be honest what would be even more ideal would be to temporarily move the data file for the streamed torrent to a different directory. That way I could set up a plex media library called "Downloading" which would point to that folder. Then all I have to do is put up a torrent for streaming and on any browser/smart tv/mac go to the downloading library and start watching. Only issue I can think of is that your mechanism for downloading the part being watched might not work with it).

Two last things. First, how do I stop a torrent from streaming? Second, if adding a status bar for opening up a stream wouldn't be too hard to add I would enjoy the feature.

**Comment by JohnDoee** [comment]
I'm happy you got it working, the old version is from 2011.

The pixelation is a known bug, so don't worry too much about it.

If you can find a way to mount a HTTP file, that's the only Plex solution I can come up with. Google did not yield any good results on that (although it should be technically possible to do so).

There isn't much point in stopping the streaming as it doesn't do much. If you just leave it be, it'll go back to normal eventually. If there is something specific you want it to do, then that'd be a better request.

A status bar might be a good idea, I'll create a new ticket for it.

**Comment by gustebeast** [comment]
So I presume you use html some how to detect what part to download, so simply opening up the partially downloaded .mkv in plex while streaming wouldnt work.

Perhaps it could still be done though. Basically the case is when a file is being streamed but no one is accessing it via the html link. I'm not sure what this plugin does now, but I might guess it doesnt do anything because no one is asking it to. What if, in this case when no one is accessing it, the plugin defaults to simple sequential downloading mode. So if a torrent is downloading, I click "stream this file", and then dont connect to it via VLC, it will download it as if someone was watching it via html from start to finish with no tracking. For a completed torrent, it still wouldnt do anything since the torrent file is already completely downloaded. This way I could start a stream and then just select the downloading .mkv using plex and start watching (as long as I dont track, and if I really need to I can just use VLC)

**Comment by JohnDoee** [comment]
You got somewhat lucky, if you're not streaming it becomes less and less sequential. When you don't start the stream via the link, it assumes you are still at byte 0. The buffer is based on where the plugin think you are in the file, i.e. byte 0. When there is a lot of buffer, it will become less sequential (but still tries to download sequentially).

If your internet can download a movie a bit faster than you watch it, you can probably watch most movies without too many problems.

**Comment by gustebeast** [comment]
I just saw this setting in plex, not sure if its applicable:
"Use the experimental video player, which supports streaming to the HTML5 video element instead of the Flash player. Requires Plex Media Server 0.9.8.6 or later."

**Comment by gustebeast** [comment]
How would you recommend setting
UPnP
NAT-PMP
Peer Exchange
LSD
DHT

**Comment by JohnDoee** [comment]
I did check up on the Plex stuff. The only way seems to be to make a plugin for Plex and that is a bit beyond this project.

Just enable everything, the client knows when to use what.

http://news.softpedia.com/images/extra/LINUX/large/delugeappofthemonthjune09-large_002.jpg <- this looks like a good setup, except "Maximum upload slots" can be increased a lot more to e.g. unlimited (-1) or 50 or something else big. With private trackers, it doesn't matter much if it is very big.

There are four things that can cause problems with seeding and I can tell them to you without checking.
* Not enough upload slots - other torrents are using the number of slots. That's one of the things you can change in the bandwidth menu.
* Port not forwarded - There's a fine menu to check for that stuff in Deluge under network.
* Nobody else is downloading the torrent - most common reason, really.
* Tracker is broken - It happens.

**Comment by gustebeast** [comment]
Yeah, I'm getting seeds on one tracker and not another so its easier some weird compatibility thing or I'm just really unlucky. Anyway thanks for the help and will be definitely be using this awesome plugin next time I need to watch something ASAP.
