### ISSUE TITLE
Needs option to use HTTP header "Content-Disposition: inline"

### ISSUE THREAD

**Issue by Keavon** [JohnDoee/deluge-streaming#21]
At present, files served with this plug-in are given the `Content-Disposition: attachment` HTTP response header which causes the browser to treat it as a file that must be downloaded to disk. For example, this is the header for a torrent:

```
Content-Disposition: attachment; filename=Sintel.2010.1080p.mp4
```

Streaming downloaded files directly in the browser would be extremely handy so it isn't necessary to save it to disk first (or open it in an external application like VLC). Please add the option to respond with the `Content-Disposition: inline` header either as a configuration setting, or as a pair of context menu entries designated "Stream this file" and "Download this file".

**Comment by JohnDoee** [comment]
That'd be a web-ui only feature, I guess. Do you want it to just open the video in a new window and try to start playing it ?

**Comment by Keavon** [comment]
At the moment I am able to just click the link that gets shown and it opens in a new tab and begins the download. Using [this Chrome extension to remove the `Content-Disposition: attachment` header](https://chrome.google.com/webstore/detail/undisposition/hjfncfijclafkkfifjelofbeclipplfi?hl=en) it opens in a new tab and plays the video with the default Chrome video player controls. Whether a hosted page embedding the video is used, or the file is just served inline, I am not too concerned. In theory, other non-video file types might also be cool, like audio or image file types, but of course video is the most common use case.

**Comment by Keavon** [comment]
For example, it could look like this:
![Mock-up](https://user-images.githubusercontent.com/4388688/52779717-92f0d980-2ffd-11e9-90a2-9e2961fb77b5.png)

The first button, `Stream file (browser)`, could directly open the file in a new tab with `Content-Disposition: inline` like so:

![In-browser playback](https://user-images.githubusercontent.com/4388688/52780085-4f4a9f80-2ffe-11e9-9b13-7dd63076caba.png)

The second link, `Stream file (link)`, could open the dialog with the link available to copy as it currently works (or even just forgo the dialog and copy it straight into the user's clipboard):

![Stream link](https://user-images.githubusercontent.com/4388688/52779862-d9463880-2ffd-11e9-9603-598df23abf5e.png)

**Comment by JohnDoee** [comment]
I added an additional button.

You probably realize a lot of video content wont play without something to transcode the audio. That's a different project that'll probably be integrated at some point though.
