### ISSUE TITLE
Download Start 'n End Points

### ISSUE THREAD

**Issue by Mike-Reddick** [JohnDoee/deluge-streaming#25]
To me is impossible use you plugin because my internet isn't so fast, I want ask you please to add an feature so, add a new context menu not to streaming but, to set an start and an end point to download in the specific file. Why, for instance, have MMA events with have 10 gb, just the main event, and I want just the last fight, so I can set to download just the last 2,5 gb of the file. Is like the Pieces plugin but per file.

Thanks so much!

**Comment by JohnDoee** [comment]
This is the wrong project for specifying which part of a file you want to download (exactly). Try the pieces plugin instead, with that you can specify exactly which pieces you want.
