### ISSUE TITLE
Percentages Messing Up

### ISSUE THREAD

**Issue by gustebeast** [JohnDoee/deluge-streaming#4]
When I start to stream a file two things happen.

1. The percentages get messed up. See -------------
I think it may have something to do with the "Do not download" thing, but not completely sure.

2. My download speed sharply declines for maybe 20 seconds then picks back up. This obviously could just be chance, but it has happened several times now. Would this plugin affect download speed?

**Comment by gustebeast** [comment]
Also, I've started using a different apache folder directory style ( https://larsjung.de/h5ai/ ). Aside from looking nice, it actually allows you to watch .mkv files in your browser. This seems like it must be some kind of html stream so would it function with this plugin? Like would the plugin know where you are in the file and thus support scanning and such.

**Comment by JohnDoee** [comment]
Contacted you elsewhere, look around and see if you can find it.

**Comment by JohnDoee** [comment]
Fixed
