### ISSUE TITLE
partial torrent download became full download after attempt to stream

### ISSUE THREAD

**Issue by sormy** [JohnDoee/deluge-streaming#6]

**Comment by jakubbroz** [comment]
Same problem.

**Comment by JohnDoee** [comment]
Sorry about the delay but didn't get around to check up on this.

Do you mean the file you're streaming or all the files in the torrent ? More importantly, what do you expect it to do ?

Currently it will download the whole file you tried to stream but not download any of the other files. That seems to work, at least for me.

**Comment by K1773R** [comment]
@JohnDoee there should be a setting to either only download the requested file, or download everything and let the torrent run.

**Comment by JohnDoee** [comment]
@K1773R There was already something like that in it, although it might not have been very clear.

Anyways, probably not going to add partial file support as it seems like something that can end up very wonky.
