### ISSUE TITLE
How to open the `stream+http://` protocol?

### ISSUE THREAD

**Issue by ikzk** [JohnDoee/deluge-streaming#8]
Sorry that I cannot open it directly and I have to use it by copying the link and then deleting the `stream+` and then playing the link by `mpv http://...`. Anything better I can do with the `stream+http://` link that the plugin provides? Thanks.

**Comment by JohnDoee** [comment]
You can disable it, it's a checkbox in options called "use stream urls" - it should be disabled per default.

You CAN do something better with them, you can use it in combination with http://streamprotocol.tidalstream.org/ which turns them into clickable urls that are opened directly by a media player.

The idea is to make a pipeline where you can connect everything without copy/pasting urls and make it easy to turn a torrent site into a streaming site.

* Pick video player in streamprotocol tray icon
* click stream+http url and its opened directly in your media player.

**Comment by ikzk** [comment]
@JohnDoee Cool! Thanks for your detailed explanation. That helps me a lot!
